name: Delete workflow runs

on:
  push:
  schedule:
    - cron:  '0 0 * * *'
  
env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit
        run: |
          set -x
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add --all && git commit -m "Add files" && git push --force
          git reset $(git commit-tree HEAD^{tree} -m "Commit")
          git push --force
      - name: Delete workflow runs
        run: |
          gh api -X GET /repos/${{ github.repository }}/actions/runs \
            | jq '.workflow_runs[] | .id' \
            | tail -n +4 \
            | xargs -n1 -I % gh api repos/${{ github.repository }}/actions/runs/% -X DELETE
